### PR TITLE
Allow slide cropping in both Anki card questions and answers.  Fix of Issue #3.

### PR DESCRIPTION
**Pull request by barryridge**
Hi again!

I really wanted this feature, so I decided to push ahead with developing it.  It required some substantial changes to the original codebase, but I think it's worked out fairly well and I hope you'll consider integrating them into the project.  I would encourage you to test it out first though, if you have time, just to make sure everything is working as it should.  I have included some more unit tests, updated the test file to include an example of slide cropping, and updated the README with instructions on how to use it.

I'm still getting the hang of this whole PR business, so if I've done things the wrong way, please let me know and I'll try to fix it.

Best wishes,
Barry

### CODE REVIEW

**Comment by musically-ut** [comment]
Hi! 

These look great!

I would request you to do a `git rebase upstream/master` against my `master` branch to include some of the commits I had made to make the code compatible with Python 3 and then do a `git push -f` to update this PR. That will fix the current conflicts.

I'll test it out the next time I get a chance. 

Thanks again!

**Comment by barryridge** [comment]
Just noticed some errors in the README actually- the numerical notation should be along the lines of `[[0:100], [0:100]]` (or `[[0-100], [0-100]]` - it parses both), not `[[0,100], [0,100]]` - I'll fix that and also apply the other fixes you suggested.

-B

**Comment by barryridge** [comment]
The rebase didn't look so easy, since I had modified some of the functions that had changed since you did that Python 3 update.  So instead, I've just updated everything from your Python 3 update by hand- I think it should be OK now.

**Comment by musically-ut** [comment]
Thanks!

I've manually merged in the commits after running some tests locally. 👍

**Pull request merged**
